name: Run K6 Tests

on:
  push:
    branches: [main]

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install K6
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common
          sudo gpg -k
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install k6

      - name: Execute smoke testing
        run: k6 run ./Scripts/smoke-testing.js

      - name: Execute load testing
        run: k6 run ./Scripts/load-testing.js